#ifndef TILESPRITES_H
#define TILESPRITES_H

#include <stdint.h>
#include "img.h"

#define TILE_SPRITE_WIDTH 9
#define TILE_SPRITE_HEIGHT 11
#define TILE_SOURCE_WIDTH 16
#define TILE_SOURCE_HEIGHT 16
#define TILE_CHROMA_KEY 0x07E0
#define LARGE_TREE_WIDTH 56
#define LARGE_TREE_HEIGHT 82
#define SMALL_TREE_WIDTH 36
#define SMALL_TREE_HEIGHT 56

struct TileSpriteEntry {
    uint8_t gridX;
    uint8_t gridY;
    ImageData image;
};

extern const uint32_t TileSpriteCount;
extern const TileSpriteEntry TileSprites[];
extern const uint16_t LargeTreeSprite[LARGE_TREE_WIDTH * LARGE_TREE_HEIGHT];
extern ImageData LargeTreeImage;
extern const uint16_t SmallTreeSprite[SMALL_TREE_WIDTH * SMALL_TREE_HEIGHT];
extern ImageData SmallTreeImage;

// Platform surface pieces from tileset row 4, columns 5-9.
#define PlatformLeftEndImage TileImage_05_04
#define PlatformMiddleAImage TileImage_06_04
#define PlatformMiddleBImage TileImage_07_04
#define PlatformMiddleCImage TileImage_08_04
#define PlatformRightEndImage TileImage_09_04

void DrawBitmapChroma(int16_t x, int16_t y, const uint16_t *image, int16_t w, int16_t h, uint16_t chroma);
void DrawImageChroma(int16_t x, int16_t y, ImageData image, uint16_t chroma = TILE_CHROMA_KEY);
void DrawPlatformRun(int16_t x, int16_t y, uint8_t tiles);
void DrawExampleLevel(void);

extern const uint16_t TileSprite_00_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_00;
extern const uint16_t TileSprite_01_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_00;
extern const uint16_t TileSprite_02_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_00;
extern const uint16_t TileSprite_03_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_00;
extern const uint16_t TileSprite_04_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_00;
extern const uint16_t TileSprite_05_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_00;
extern const uint16_t TileSprite_06_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_00;
extern const uint16_t TileSprite_13_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_00;
extern const uint16_t TileSprite_14_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_00;
extern const uint16_t TileSprite_15_00[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_00;
extern const uint16_t TileSprite_12_01[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_01;
extern const uint16_t TileSprite_13_01[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_01;
extern const uint16_t TileSprite_14_01[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_01;
extern const uint16_t TileSprite_15_01[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_01;
extern const uint16_t TileSprite_16_01[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_01;
extern const uint16_t TileSprite_00_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_02;
extern const uint16_t TileSprite_01_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_02;
extern const uint16_t TileSprite_02_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_02;
extern const uint16_t TileSprite_11_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_11_02;
extern const uint16_t TileSprite_12_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_02;
extern const uint16_t TileSprite_13_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_02;
extern const uint16_t TileSprite_14_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_02;
extern const uint16_t TileSprite_15_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_02;
extern const uint16_t TileSprite_16_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_02;
extern const uint16_t TileSprite_17_02[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_17_02;
extern const uint16_t TileSprite_00_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_03;
extern const uint16_t TileSprite_01_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_03;
extern const uint16_t TileSprite_02_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_03;
extern const uint16_t TileSprite_03_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_03;
extern const uint16_t TileSprite_04_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_03;
extern const uint16_t TileSprite_11_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_11_03;
extern const uint16_t TileSprite_12_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_03;
extern const uint16_t TileSprite_13_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_03;
extern const uint16_t TileSprite_14_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_03;
extern const uint16_t TileSprite_15_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_03;
extern const uint16_t TileSprite_16_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_03;
extern const uint16_t TileSprite_17_03[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_17_03;
extern const uint16_t TileSprite_00_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_04;
extern const uint16_t TileSprite_01_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_04;
extern const uint16_t TileSprite_02_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_04;
extern const uint16_t TileSprite_03_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_04;
extern const uint16_t TileSprite_04_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_04;
extern const uint16_t TileSprite_05_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_04;
extern const uint16_t TileSprite_06_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_04;
extern const uint16_t TileSprite_07_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_04;
extern const uint16_t TileSprite_08_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_04;
extern const uint16_t TileSprite_09_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_04;
extern const uint16_t TileSprite_11_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_11_04;
extern const uint16_t TileSprite_12_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_04;
extern const uint16_t TileSprite_13_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_04;
extern const uint16_t TileSprite_14_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_04;
extern const uint16_t TileSprite_15_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_04;
extern const uint16_t TileSprite_16_04[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_04;
extern const uint16_t TileSprite_00_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_05;
extern const uint16_t TileSprite_01_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_05;
extern const uint16_t TileSprite_02_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_05;
extern const uint16_t TileSprite_03_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_05;
extern const uint16_t TileSprite_04_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_05;
extern const uint16_t TileSprite_05_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_05;
extern const uint16_t TileSprite_06_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_05;
extern const uint16_t TileSprite_07_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_05;
extern const uint16_t TileSprite_08_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_05;
extern const uint16_t TileSprite_09_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_05;
extern const uint16_t TileSprite_12_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_05;
extern const uint16_t TileSprite_13_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_05;
extern const uint16_t TileSprite_14_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_05;
extern const uint16_t TileSprite_15_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_05;
extern const uint16_t TileSprite_16_05[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_05;
extern const uint16_t TileSprite_00_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_06;
extern const uint16_t TileSprite_01_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_06;
extern const uint16_t TileSprite_02_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_06;
extern const uint16_t TileSprite_03_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_06;
extern const uint16_t TileSprite_04_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_06;
extern const uint16_t TileSprite_05_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_06;
extern const uint16_t TileSprite_06_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_06;
extern const uint16_t TileSprite_07_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_06;
extern const uint16_t TileSprite_08_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_06;
extern const uint16_t TileSprite_09_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_06;
extern const uint16_t TileSprite_12_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_06;
extern const uint16_t TileSprite_13_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_06;
extern const uint16_t TileSprite_14_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_06;
extern const uint16_t TileSprite_15_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_06;
extern const uint16_t TileSprite_16_06[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_06;
extern const uint16_t TileSprite_00_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_07;
extern const uint16_t TileSprite_01_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_07;
extern const uint16_t TileSprite_02_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_07;
extern const uint16_t TileSprite_03_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_07;
extern const uint16_t TileSprite_06_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_07;
extern const uint16_t TileSprite_07_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_07;
extern const uint16_t TileSprite_09_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_07;
extern const uint16_t TileSprite_13_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_07;
extern const uint16_t TileSprite_14_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_07;
extern const uint16_t TileSprite_15_07[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_07;
extern const uint16_t TileSprite_00_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_08;
extern const uint16_t TileSprite_01_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_08;
extern const uint16_t TileSprite_02_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_08;
extern const uint16_t TileSprite_03_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_08;
extern const uint16_t TileSprite_04_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_08;
extern const uint16_t TileSprite_05_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_08;
extern const uint16_t TileSprite_06_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_08;
extern const uint16_t TileSprite_07_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_08;
extern const uint16_t TileSprite_08_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_08;
extern const uint16_t TileSprite_09_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_08;
extern const uint16_t TileSprite_10_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_10_08;
extern const uint16_t TileSprite_11_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_11_08;
extern const uint16_t TileSprite_12_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_08;
extern const uint16_t TileSprite_13_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_08;
extern const uint16_t TileSprite_14_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_08;
extern const uint16_t TileSprite_15_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_08;
extern const uint16_t TileSprite_16_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_08;
extern const uint16_t TileSprite_17_08[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_17_08;
extern const uint16_t TileSprite_00_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_09;
extern const uint16_t TileSprite_01_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_09;
extern const uint16_t TileSprite_02_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_09;
extern const uint16_t TileSprite_03_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_09;
extern const uint16_t TileSprite_04_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_09;
extern const uint16_t TileSprite_05_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_09;
extern const uint16_t TileSprite_06_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_09;
extern const uint16_t TileSprite_07_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_09;
extern const uint16_t TileSprite_08_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_09;
extern const uint16_t TileSprite_09_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_09;
extern const uint16_t TileSprite_10_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_10_09;
extern const uint16_t TileSprite_11_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_11_09;
extern const uint16_t TileSprite_12_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_12_09;
extern const uint16_t TileSprite_13_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_13_09;
extern const uint16_t TileSprite_14_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_14_09;
extern const uint16_t TileSprite_15_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_15_09;
extern const uint16_t TileSprite_16_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_16_09;
extern const uint16_t TileSprite_17_09[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_17_09;
extern const uint16_t TileSprite_00_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_00_10;
extern const uint16_t TileSprite_01_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_01_10;
extern const uint16_t TileSprite_02_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_02_10;
extern const uint16_t TileSprite_03_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_03_10;
extern const uint16_t TileSprite_04_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_04_10;
extern const uint16_t TileSprite_05_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_05_10;
extern const uint16_t TileSprite_06_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_06_10;
extern const uint16_t TileSprite_07_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_07_10;
extern const uint16_t TileSprite_08_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_08_10;
extern const uint16_t TileSprite_09_10[TILE_SPRITE_WIDTH * TILE_SPRITE_HEIGHT];
extern ImageData TileImage_09_10;

#endif
